name: Continuous integration
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.5.2
        with:
          default: true
          ldproxy: true
      - name: Release build std
        uses: actions-rs/cargo@v1
        with:
          command: check
